name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  test-project:
    name: Generate and Test Project (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Simple Project"
            extra_vars: ""
          - name: "With Different Module Name"
            extra_vars: "module_name=\"test_project\""

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Cookiecutter
        run: pip install cookiecutter

      - name: Generate project from template
        run: |
          python3 -m cookiecutter gh:mohammadraziei/cookiecutter-python-template \
            --no-input \
            project_name="ci test project" \
            description="Test project" \
            author_name="Test Author" \
            author_email="test@example.com" \
            git_username="testuser" \
            ${{ matrix.extra_vars }}
          mv ci-test-project/* . && rm -r ci-test-project

      - name: Install dependencies for generated project
        run: |
          pip install -r requirements.txt
          pip install hatch pytest-cov ruff build

      - name: Run Ruff linter
        run: |
          ruff check . 
          # or
          hatch run lint:all

      - name: Run tests with pytest
        run: |
          pytest --cov --cov-report=term
          # or
          hatch run test

      - name: Build the package
        run: |
          python -m build
          # or
          hatch build

      - name: Install the built package
        run: pip install dist/*.whl

  # Badge job (using shields.io)
  badge:
    name: Test Status Badge
    needs: [test-project]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Create test badge
        uses: emibcn/badge-action@v2
        with:
          label: 'tests'
          status: ${{ needs.test-project.result }}
          color: ${{ needs.test-project.result == 'success' && 'brightgreen' || 'red' }}
          path: test-badge.svg