name: CI

on:
  push:
    branches: [master] # Note: Consider changing 'master' to 'main' if that's your default branch
  pull_request:
  workflow_dispatch:

jobs:
  test-project: # New job for testing
    name: Generate and Test Project from Template
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Cookiecutter
        run: pip install cookiecutter

      - name: Generate project from template
        run: |
          python3 -m cookiecutter gh:mohammadraziei/cookiecutter-python-template --no-input project_name="test_project" description="Test project" author_name="Test Author" author_email="test@example.com" git_username="testuser"
          mv test-project/* .
          rm -r test-project
                
      - name: Set up Python for generated project
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies for generated project
        run: |
          pip install -r requirements.txt
          pip install hatch pytest-cov ruff

      - name: Run Ruff linter
        run: ruff check . 

      - name: Run tests with pytest
        run: pytest --cov --cov-report=term

      - name: Build the package
        run: hatch build

      - name: Install the built package
        run: pip install dist/*.whl

  # Badge job (using shields.io)
  badge:
    name: Test Status Badge
    needs: test-project # Now depends on the second job
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Create test badge
        uses: emibcn/badge-action@v2
        with:
          label: 'tests'
          status: ${{ needs.test-project.result }} # Check result of the second job
          color: ${{ needs.test-project.result == 'success' && 'brightgreen' || 'red' }}
          path: test-badge.svg